swagger: '2.0'
info:
    title: Filmes
    version: 1.0.0
    description: 'Api para testar o open api generator '
    contact:
        name: Filmes
    license:
        name: MIT License
        url: 'https://opensource.org/licenses/MIT'
consumes:
    - application/json
produces:
    - application/json
paths:
    /filmes:
        get:
            responses:
                '200':
                    description: Successful response - returns an array of `filmes` entities.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/filmes'
            operationId: getfilmes
            summary: List All filmes
            description: Gets a list of all `filmes` entities.
        post:
            parameters:
                -
                    name: body
                    description: A new `filmes` to be created.
                    schema:
                        $ref: '#/definitions/filmes'
                    in: body
                    required: true
            responses:
                '201':
                    description: Successful response.
                    schema:
                        $ref: '#/definitions/filmes'
            operationId: createFilmes
            summary: Create a filmes
            description: Creates a new instance of a `filmes`.
    '/filmes/{filmesId}':
        get:
            responses:
                '200':
                    description: Successful response - returns a single `filmes`.
                    schema:
                        $ref: '#/definitions/filmes'
            operationId: getfilmesbyid
            summary: Get a filmes
            description: Gets the details of a single instance of a `filmes`.
        put:
            parameters:
                -
                    name: body
                    description: Updated `filmes` information.
                    schema:
                        $ref: '#/definitions/filmes'
                    in: body
                    required: true
            responses:
                '202':
                    description: Successful response.
                    schema:
                        $ref: '#/definitions/filmes'
            operationId: updatefilmes
            summary: Update a filmes
            description: Updates an existing `filmes`.
        delete:
            responses:
                '204':
                    description: Successful response.
            operationId: deletefilmes
            summary: Delete a filmes
            description: Deletes an existing `filmes`.
        parameters:
            -
                name: filmesId
                description: A unique identifier for a `filmes`.
                in: path
                required: true
                type: string
definitions:
    filmes:
        title: Root Type for filmes
        description: ''
        type: object
        properties:
            id:
                format: int32
                type: integer
            nome:
                type: string
            genero:
                type: string
            sinopse:
                type: string
            data de estreia:
                type: string
        example:
            id: 1
            nome: nome do filme
            genero: genero do filme
            sinopse: sinopse do filme
            data de estreia: data de estreia do filme
securityDefinitions:
    filme:
        type: basic
        description: banco de filmes
