spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmes?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 13245
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
